### Notebook to count the number of tokens (words) in legal datasets

Ciation: Sean Rehaag, "Notebook to count the number of tokens (words) in legal datasets" (2025), online: <https://github.com/a2aj-ca/canadian-legal-data> (updated March 15, 2026).

In [1]:
import tiktoken
from datasets import load_dataset
import pandas as pd
from tqdm import tqdm

# Enable progress bar for pandas operations
tqdm.pandas()

# load all legislation / regulations
laws = load_dataset("a2aj/canadian-laws", split="train")
cases = load_dataset("a2aj/canadian-case-law", split="train")
# covert to df
df_laws = laws.to_pandas()
df_cases = cases.to_pandas()

# count tokens
def count_tokens(text):
    if not text:
        return 0
    encoding = tiktoken.encoding_for_model("gpt-3.5-turbo")
    tokens = encoding.encode(text)
    return len(tokens)

print("\nCounting tokens for laws (English)...")
df_laws['token_count_en'] = df_laws['unofficial_text_en'].progress_apply(count_tokens)

print("Counting tokens for laws (French)...")
df_laws['token_count_fr'] = df_laws['unofficial_text_fr'].progress_apply(count_tokens)

print("Counting tokens for cases (English)...")
df_cases['token_count_en'] = df_cases['unofficial_text_en'].progress_apply(count_tokens)

print("Counting tokens for cases (French)...")
df_cases['token_count_fr'] = df_cases['unofficial_text_fr'].progress_apply(count_tokens)

# get sum for cases
total_case_tokens = df_cases['token_count_en'].sum() + df_cases['token_count_fr'].sum()
total_law_tokens = df_laws['token_count_en'].sum() + df_laws['token_count_fr'].sum()

print(f"\nResults:")
print(f"Cases: {total_case_tokens:,} tokens")
print(f"Laws: {total_law_tokens:,} tokens")
print(f"Total: {total_case_tokens + total_law_tokens:,} tokens")
print("Assuming an average of 750 words per 1000 tokens:")
print(f"Total: {(total_case_tokens + total_law_tokens) * 750 / 1000:,} words")

README.md: 0.00B [00:00, ?B/s]

LEGISLATION-FED/train.parquet:   0%|          | 0.00/81.4M [00:00<?, ?B/s]

REGULATIONS-FED/train.parquet:   0%|          | 0.00/70.2M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/5796 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

BCCA/train.parquet:   0%|          | 0.00/182M [00:00<?, ?B/s]

BCSC/train.parquet:   0%|          | 0.00/886M [00:00<?, ?B/s]

CHRT/train.parquet:   0%|          | 0.00/45.0M [00:00<?, ?B/s]

CMAC/train.parquet:   0%|          | 0.00/4.62M [00:00<?, ?B/s]

FC/train.parquet:   0%|          | 0.00/821M [00:00<?, ?B/s]

FCA/train.parquet:   0%|          | 0.00/141M [00:00<?, ?B/s]

ONCA/train.parquet:   0%|          | 0.00/178M [00:00<?, ?B/s]

RAD/train.parquet:   0%|          | 0.00/312M [00:00<?, ?B/s]

RLLR/train.parquet:   0%|          | 0.00/5.82M [00:00<?, ?B/s]

RPD/train.parquet:   0%|          | 0.00/148M [00:00<?, ?B/s]

SCC/train.parquet:   0%|          | 0.00/360M [00:00<?, ?B/s]

SST/train.parquet:   0%|          | 0.00/220M [00:00<?, ?B/s]

TCC/train.parquet:   0%|          | 0.00/204M [00:00<?, ?B/s]

YKCA/train.parquet:   0%|          | 0.00/3.96M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/191372 [00:00<?, ? examples/s]

Counting tokens for laws (English)...

100%|██████████| 5796/5796 [00:05<00:00, 1149.56it/s]

Counting tokens for laws (French)...

100%|██████████| 5796/5796 [00:06<00:00, 889.93it/s]

Counting tokens for cases (English)...

100%|██████████| 191372/191372 [03:28<00:00, 919.11it/s]

Counting tokens for cases (French)...

100%|██████████| 191372/191372 [02:17<00:00, 1394.94it/s]

Results:
Cases: 1,755,018,604 tokens
Laws: 55,916,365 tokens
Total: 1,810,934,969 tokens
Assuming an average of 750 words per 1000 tokens:
Total: 1,358,201,226.75 words

In [2]:
# make cases table with token counts
import requests
import pandas as pd

# Set url
url = "https://api.a2aj.ca/coverage"

# Get parameters
doc_type = "cases" 
parameters = f"doc_type={doc_type}"

# Get data
request = requests.get(f"{url}?{parameters}")
data = request.json()

# Convert to dataframe
df_cases_coverage = pd.DataFrame(data['results'])

# Create new col, token_count, sum of df.token_count_en and df.token_count fr
df_cases["token_count"] = df_cases["token_count_en"] + df_cases["token_count_fr"]

# Create new df_cases_summary groupby datasets
df_cases_tokens = df_cases.groupby("dataset").agg({"token_count": "sum"}).reset_index()

# Merge on dataset
df_cases_coverage = df_cases_coverage.merge(df_cases_tokens, on="dataset")

# Drop description_fr
df_cases_coverage = df_cases_coverage.drop(columns=["description_fr"])

df_cases_coverage

,dataset,description_en,earliest_document_date,latest_document_date,number_of_documents,token_count
0,BCCA,British Columbia Court of Appeal,1999-01-04,2026-03-13,14418,80746444
1,BCSC,Supreme Court of British Columbia,2000-01-04,2026-03-12,50717,390173471
2,CHRT,Canadian Human Rights Tribunal,2003-01-10,2026-02-02,1110,23283586
3,CMAC,Court Martial Appeal Court,2001-01-19,2026-01-15,151,2414607
4,FC,Federal Court,2001-02-01,2026-03-13,35198,423214228
5,FCA,Federal Court of Appeal,2001-02-01,2026-03-13,7716,76020955
6,ONCA,Ontario Court of Appeal,1998-06-08,2026-03-13,23667,79948280
7,RAD,Refugee Appeal Division (IRB),2013-02-19,2025-08-11,14122,174199033
8,RLLR,"Refugee Law Lab Reporter (RPD, IRB)",2019-01-07,2024-12-13,927,2552201
9,RPD,Refugee Protection Division (IRB),2002-07-16,2020-12-14,6729,79241147
10,SCC,Supreme Court of Canada,1877-01-15,2026-03-06,10869,181785817
11,SST,Social Security Tribunal,2013-03-08,2026-02-18,17458,129010088
12,TCC,Tax Court of Canada,2003-01-21,2026-03-10,8021,110662925
13,YKCA,Yukon Court of Appeal,2000-05-15,2026-01-19,269,1765822

In [3]:
# make laws table with token counts
import requests
import pandas as pd

# Set url
url = "https://api.a2aj.ca/coverage"

# Get parameters
doc_type = "laws" 
parameters = f"doc_type={doc_type}"

# Get data
request = requests.get(f"{url}?{parameters}")
data = request.json()

# Convert to dataframe
df_laws_coverage = pd.DataFrame(data['results'])

# Create new col, token_count, sum of df.token_count_en and df.token_count fr
df_laws["token_count"] = df_laws["token_count_en"] + df_laws["token_count_fr"]

# Create new df_cases_summary groupby datasets
df_laws_tokens = df_laws.groupby("dataset").agg({"token_count": "sum"}).reset_index()

# Merge on dataset
df_laws_coverage = df_laws_coverage.merge(df_laws_tokens, on="dataset")

# Drop description_fr
df_laws_coverage = df_laws_coverage.drop(columns=["description_fr"])

df_laws_coverage

,dataset,description_en,earliest_document_date,latest_document_date,number_of_documents,token_count
0,LEGISLATION-FED,Federal Statutes,1870-05-12,2025-06-26,954,28684522
1,REGULATIONS-FED,Federal Regulations,1945-12-21,2026-02-11,4842,27231843